SmDanceBotWareHouse3:
  ros__parameters:
    odom_tracker:
      odom_frame: odom
      record_point_distance_threshold:  0.01 # 1 cm
      record_angular_distance_threshold: 0.01 # rads
      clear_point_distance_threshold: 0.5 # 0.5m
      clear_angular_distance_threshold: 0.6 # rads
