<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sm_cl_px4_mr_test_1</name>
  <version>0.1.0</version>
  <description>SMACC2 test state machine for cl_px4_mr multirotor client</description>
  <maintainer email="brett@robosoft.ai">Brett Aldrich</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>smacc2</depend>
  <depend>cl_px4_mr</depend>
  <depend>cl_ros2_timer</depend>
  <depend>px4_msgs</depend>
  <depend>rclcpp</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
