SmDanceBotWareHouse3:
  ros__parameters:
    odom_tracker:
      odom_frame: odom
      record_point_distance_threshold:  0.01 # 1 cm
      record_angular_distance_threshold: 0.01 # rads
      clear_point_distance_threshold: 0.15 # 5cm
      clear_angular_distance_threshold: 0.2 # rads
