state_machine_rosparam_ws: /SmAtomicPerformanceTestA3
success_switch:
   - type: state_reached
     state_name: "sm_atomic_performance_test_a_3::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
