controller_names:
  #- scaled_joint_trajectory_controller
  - joint_trajectory_controller_ur5_1


scaled_joint_trajectory_controller_ur5_1:
  #action_ns: follow_joint_trajectory_ur5_1
  action_ns: /follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - ur5_1shoulder_pan_joint
    - ur5_1shoulder_lift_joint
    - ur5_1elbow_joint
    - ur5_1wrist_1_joint
    - ur5_1wrist_2_joint
    - ur5_1wrist_3_joint


joint_trajectory_controller_ur5_1:
  #action_ns: follow_joint_trajectory_ur5_1
  action_ns: /follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - ur5_1shoulder_pan_joint
    - ur5_1shoulder_lift_joint
    - ur5_1elbow_joint
    - ur5_1wrist_1_joint
    - ur5_1wrist_2_joint
    - ur5_1wrist_3_joint
