// Copyright 2025 Robosoft Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// sm_mode_state_behavior_1: Demonstrates a client behavior (CbDefaultKeyboardBehavior)
// defined at the mode state level (MsRunning), persisting across all inner superstate
// and leaf state transitions.
//
// Because keyboard behavior lives ONLY in MsRunning (not in leaf states), every keypress
// generates exactly ONE event regardless of which inner state is active. This avoids the
// double-event problem that would occur if leaf states also had keyboard behaviors.
//
// Key interactions:
//   'f' — switch between SsPhase1 and SsPhase2 (handled at superstate level)
//   'n' — advance to next leaf state (handled at leaf level, event from MsRunning's behavior)
//   timer — auto-advance leaf state (3s in SsPhase1, 5s in SsPhase2)
//
// Architecture highlights:
//   - MsRunning owns the single CbDefaultKeyboardBehavior in OrKeyboard
//   - Leaf states have ONLY CbTimerCountdownOnce — no keyboard behavior
//   - EvKeyPressN reactions in leaf states react to events generated by MsRunning's behavior
//   - EvKeyPressF reactions in SsPhase1/SsPhase2 react to events from the same source
//   - MsRunning's keyboard behavior survives SsPhase1 <-> SsPhase2 switches

#pragma once

#include <smacc2/smacc.hpp>

// CLIENTS
#include <cl_keyboard/cl_keyboard.hpp>
#include <cl_ros2_timer/cl_ros2_timer.hpp>

// CLIENT BEHAVIORS
#include <cl_keyboard/client_behaviors/cb_default_keyboard_behavior.hpp>
#include <cl_ros2_timer/client_behaviors/cb_timer_countdown_once.hpp>

// ORTHOGONALS
#include <sm_mode_state_behavior_1/orthogonals/or_keyboard.hpp>
#include <sm_mode_state_behavior_1/orthogonals/or_timer.hpp>

using namespace boost;
using namespace smacc2;
using namespace smacc2::default_events;
using namespace cl_ros2_timer;
using namespace cl_keyboard;
using namespace std::chrono_literals;

namespace sm_mode_state_behavior_1
{
// Forward declarations
class MsRunning;
struct SsPhase1;
struct SsPhase2;
struct StPhaseA;
struct StPhaseB;
struct StPhaseC;
struct StPhaseX;
struct StPhaseY;

// STATE MACHINE
struct SmModeStateBehavior1 : public smacc2::SmaccStateMachineBase<SmModeStateBehavior1, MsRunning>
{
  using SmaccStateMachineBase::SmaccStateMachineBase;

  void onInitialize() override
  {
    this->createOrthogonal<OrTimer>();
    this->createOrthogonal<OrKeyboard>();
  }
};
}  // namespace sm_mode_state_behavior_1

// Include order:
//   1. Mode state first (initial state, forward-declares superstates are already done above)
//   2. Superstates (need mode state type + leaf state forward decls)
//   3. Leaf states (need superstate type)
#include <sm_mode_state_behavior_1/modestates/ms_running.hpp>
#include <sm_mode_state_behavior_1/superstates/ss_phase_1.hpp>
#include <sm_mode_state_behavior_1/superstates/ss_phase_2.hpp>
#include <sm_mode_state_behavior_1/states/st_phase_a.hpp>
#include <sm_mode_state_behavior_1/states/st_phase_b.hpp>
#include <sm_mode_state_behavior_1/states/st_phase_c.hpp>
#include <sm_mode_state_behavior_1/states/st_phase_x.hpp>
#include <sm_mode_state_behavior_1/states/st_phase_y.hpp>
