sm_aws_warehouse_navigation:
  ros__parameters:
    use_sim_time: true
    signal_detector_loop_freq: 30.0
    clear_angular_distance_threshold: 0.1 # 0.05
    clear_point_distance_threshold:  0.4 #0.1
    record_angular_distance_threshold: 0.005
    record_point_distance_threshold: 0.1
    waypoints_plan: $(pkg_share)/params/nav2z_client/waypoints_plan.yaml
    waypoints_plan_2: $(pkg_share)/params/nav2z_client/waypoints_plan2.yaml
