// Copyright 2025 Robosoft Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

namespace sm_mode_state_behavior_1
{
// SsPhase2: Second superstate within MsRunning. Contains a 2-step leaf state cycle
// (StPhaseX → StPhaseY → StPhaseX). Pressing 'f' switches back to SsPhase1.
struct SsPhase2 : smacc2::SmaccState<SsPhase2, MsRunning, StPhaseX>
{
  using SmaccState::SmaccState;

  // 'f' switches back to SsPhase1 — event generated by MsRunning's keyboard behavior
  typedef mpl::list<
    Transition<EvKeyPressF<CbDefaultKeyboardBehavior, OrKeyboard>, SsPhase1>
    > reactions;

  static void staticConfigure() {}

  void onEntry() { RCLCPP_INFO(getLogger(), "[SsPhase2] Entered (X→Y cycle, 5s each). Press 'f' to switch back to Phase1."); }

  void onExit() { RCLCPP_INFO(getLogger(), "[SsPhase2] Exiting."); }
};
}  // namespace sm_mode_state_behavior_1
