// Copyright 2025 Robosoft Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

namespace sm_mode_state_behavior_1
{
// SsPhase1: First superstate within MsRunning. Contains a 3-step leaf state cycle
// (StPhaseA → StPhaseB → StPhaseC → StPhaseA). Pressing 'f' switches to SsPhase2.
// The keyboard event for 'f' is generated by MsRunning's CbDefaultKeyboardBehavior,
// demonstrating that a parent-level behavior's events can drive superstate transitions.
struct SsPhase1 : smacc2::SmaccState<SsPhase1, MsRunning, StPhaseA>
{
  using SmaccState::SmaccState;

  // 'f' switches to SsPhase2 — event generated by MsRunning's keyboard behavior
  typedef mpl::list<
    Transition<EvKeyPressF<CbDefaultKeyboardBehavior, OrKeyboard>, SsPhase2>
    > reactions;

  static void staticConfigure() {}

  void onEntry() { RCLCPP_INFO(getLogger(), "[SsPhase1] Entered (A→B→C cycle, 3s each). Press 'f' to switch to Phase2."); }

  void onExit() { RCLCPP_INFO(getLogger(), "[SsPhase1] Exiting."); }
};
}  // namespace sm_mode_state_behavior_1
