state_machine_rosparam_ws: /SmCoretestTransitionSpeed1
success_switch:
   - type: state_reached
     state_name: "sm_coretest_transition_speed_1::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
