state_machine_rosparam_ws: /SmHuskyBarrelSearch1
success_switch:
   - type: state_reached
     state_name: "sm_husky_barrel_search_1::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
