name: Galactic Semi-Binary Build (testing)
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  push:
    branches:
      - galactic
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_repo: testing
      ros_distro: galactic
      upstream_workspace: SMACC2.galactic.repos
      ref_for_scheduled_build: galactic
