name: Rolling Binary Build (testing)
# author: Denis Štogl <denis@stoglrobotics.de>
# description: 'Build & test all dependencies from released (binary) packages.'

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '23 1 * * *'

jobs:
  binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_repo: testing
      ros_distro: rolling
      upstream_workspace: SMACC2-not-released.rolling.repos
      ref_for_scheduled_build: rolling
