name: Rolling Source Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 3 * * *'

jobs:
  rolling_source:
    runs-on: ubuntu-20.04 # ubuntu-latest
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: rolling
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          # build all packages listed in the meta package
          package-name:
             smacc2

            keyboard_client

            multirole_sensor_client
            ros_publisher_client
            ros_timer_client

            eg_conditional_generator
            eg_random_generator

            smacc2_msgs

            sm_advanced_recovery_1
            sm_atomic
            sm_atomic_performance_trace_1
            sm_atomic_subscribers_performance_test
            sm_aws_warehouse_navigation
            sm_branching
            sm_dance_bot
            sm_dance_bot_strikes_back
            sm_dance_bot_warehouse
            sm_dance_bot_warehouse_2
            sm_dance_bot_warehouse_3

            sm_multi_stage_1
            sm_respira_1
            sm_three_some

            sr_all_events_go
            sr_conditional
            sr_event_countdown

            backward_global_planner
            backward_local_planner
            forward_global_planner
            forward_local_planner
            nav2z_planners_common
            pure_spinning_local_planner
            undo_path_global_planner
            nav2z_client


          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/SMACC2.${{ env.ROS_DISTRO }}.repos?token=${{ secrets.GITHUB_TOKEN }}
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-${{ matrix.os }}
          path: ros_ws/log
